export const subscriptionPlans: Subscriptions = {
  monthly: [
    {
      title: 'Apprentice',
      value: 10,
      sub: 'per month',
      desc1: 'Create ',
      desc2: '4',
      desc3: ' stories per month',
      id: 'price_1MTrfzJdoP2TOqjtMiZl0sHc',
    },
    {
      title: 'Practicioner',
      value: 15,
      sub: 'per month',
      desc1: 'Create ',
      desc2: '12',
      desc3: ' stories per month',
      id: 'price_1MTrgYJdoP2TOqjt1dF2nJV3',
    },
    {
      title: 'Wizard',
      value: 20,
      sub: 'per month',
      desc1: 'Create ',
      desc2: '30',
      desc3: ' stories per month',
      id: 'price_1MTrhWJdoP2TOqjtSUMJp01I',
    },
  ],
  annual: [
    {
      title: 'Apprentice',
      value: 8,
      sub: 'per month / paid yearly',
      desc1: 'Create ',
      desc2: '48',
      desc3: ' stories per year',
      id: 'price_1MTriBJdoP2TOqjtaay71Jtv',
    },
    {
      title: 'Practicioner',
      value: 12,
      sub: 'per month / paid yearly',
      desc1: 'Create ',
      desc2: '144',
      desc3: ' stories per year',
      id: 'price_1MTriWJdoP2TOqjtIEKDUefH',
    },
    {
      title: 'Wizard',
      value: 15,
      sub: 'per month / paid yearly',
      desc1: 'Create ',
      desc2: '360',
      desc3: ' stories per year',
      id: 'price_1MTrjDJdoP2TOqjtyZiWJ6wu',
    },
  ],
  payPerStory: [
    {
      title: 'Apprentice',
      value: 5,
      sub: 'one-time payment',
      desc1: 'Create ',
      desc2: '1',
      desc3: ' story',
      id: 'price_1MTrjhJdoP2TOqjtjTjYC9ul',
    },
    {
      title: 'Practicioner',
      value: 20,
      sub: 'one-time payment',
      desc1: 'Create ',
      desc2: '5',
      desc3: ' stories',
      id: 'price_1MTrjxJdoP2TOqjtQwY3lyZs',
    },
    {
      title: 'Wizard',
      value: 30,
      sub: 'one-time payment',
      desc1: 'Create ',
      desc2: '15',
      desc3: ' stories',
      id: 'price_1MTrkEJdoP2TOqjttGJlbi7K',
    },
  ],
};
